import * as constantUtils from '../../../../utils/constants'

const prefix = "RE$MODULE$"

export default constantUtils.addPrefix([

  //create
  "TODO_CREATE_REQUEST_START",
  "TODO_CREATE_REQUEST_SUCCESS",
  "TODO_CREATE_REQUEST_FAILURE",

  //find
  "TODO_FIND_REQUEST_START",
  "TODO_FIND_REQUEST_SUCCESS",
  "TODO_FIND_REQUEST_FAILURE",

  //findById
  "TODO_FINDBYID_REQUEST_START",
  "TODO_FINDBYID_REQUEST_SUCCESS",
  "TODO_FINDBYID_REQUEST_FAILURE",

  //findOne
  "TODO_FINDONE_REQUEST_START",
  "TODO_FINDONE_REQUEST_SUCCESS",
  "TODO_FINDONE_REQUEST_FAILURE",

  //exists
  "TODO_EXISTS_REQUEST_START",
  "TODO_EXISTS_REQUEST_SUCCESS",
  "TODO_EXISTS_REQUEST_FAILURE",

  //count
  "TODO_COUNT_REQUEST_START",
  "TODO_COUNT_REQUEST_SUCCESS",
  "TODO_COUNT_REQUEST_FAILURE",

  //update
  "TODO_UPDATE_REQUEST_START",
  "TODO_UPDATE_REQUEST_SUCCESS",
  "TODO_UPDATE_REQUEST_FAILURE",

  //upsert
  "TODO_UPSERT_REQUEST_START",
  "TODO_UPSERT_REQUEST_SUCCESS",
  "TODO_UPSERT_REQUEST_FAILURE",

  //updateAttributes
  "TODO_UPDATEATTRIBUTES_REQUEST_START",
  "TODO_UPDATEATTRIBUTES_REQUEST_SUCCESS",
  "TODO_UPDATEATTRIBUTES_REQUEST_FAILURE",

  //delete
  "TODO_DELETE_REQUEST_START",
  "TODO_DELETE_REQUEST_SUCCESS",
  "TODO_DELETE_REQUEST_FAILURE",

  //getChangeStream
  "TODO_GETCHANGESTREAM_REQUEST_START",
  "TODO_GETCHANGESTREAM_REQUEST_SUCCESS",
  "TODO_GETCHANGESTREAM_REQUEST_FAILURE",

  //createChangeStream
  "TODO_CREATECHANGESTREAM_REQUEST_START",
  "TODO_CREATECHANGESTREAM_REQUEST_SUCCESS",
  "TODO_CREATECHANGESTREAM_REQUEST_FAILURE",

  "TODO_LIST",
  "TODO_LIST_INIT_START",

  "TODO_ITEM",
  "TODO_ITEM_INIT_START",
  "TODO_FORMFIELD_CHANGE",

],prefix)
